name: Generate GitHub Metrics

on:
  workflow_dispatch:
  push:
    branches:
      - metrics
  schedule:
    - cron: "0 * * * *"

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate General Stats Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: noumaanahmed
          template: classic
          base: header, community, repositories, metadata
          config_timezone: UTC
          config_animations: true
          filename: metrics-general.svg

      - name: Generate Recent Activity Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: noumaanahmed
          template: classic
          base: header, activity
          config_timezone: UTC
          config_animations: true
          filename: metrics-activity.svg

      - name: Display generated files (debugging step)
        run: ls -la

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          git add metrics-general.svg metrics-activity.svg
          git commit -m "Update Metrics"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
