name: Generate Metrics

on:
  # Schedule updates (each hour)
  schedule: 
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Enable the metrics you want to include
          user: noumaanahmed # Replace with your GitHub username
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          config_animations: true
